plugins {
    id 'java'
}

group = 'com.kodilla'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.40.0'
    testImplementation 'io.github.bonigarcia:webdrivermanager:5.7.0'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core:3.25.3'
    testImplementation 'org.slf4j:slf4j-api:2.0.16'
    testRuntimeOnly 'org.slf4j:slf4j-simple:2.0.16'
}

test {
    useJUnitPlatform()

    testLogging {
        events "passed", "failed", "skipped"
        showStandardStreams = true
    }
}