name: Run automated tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Create config.properties

        run: |
          mkdir -p src/test/resources
          cat > src/test/resources/config.properties << EOF
          base.url=${{ secrets.BASE_URL }}
          valid.login=${{ secrets.VALID_LOGIN }}
          valid.password=${{ secrets.VALID_PASSWORD }}
          invalid.password=wrongPassword
          empty.login=
          empty.password=
          timeout.seconds=60
          short.timeout.seconds=5
          browser=chrome
          headless=true
          EOF

      - name: Run tests
        run: ./gradlew test